### ISSUE TITLE
Feature-request: a way to mock now()

### ISSUE THREAD

**Issue by bummzack** [usebasejump/supabase-test-helpers#12]
In a lot of cases it would be extremely helpful to have the ability to mock the return value of `now()` in tests. 
Is there any chance that something like this could be added to this extension?

Here's an example implementation, which seems to make use of a separate schema and `search_path` ordering:
https://gist.github.com/thehesiod/d0314d599c721216f075375c667e2d9a

**Comment by tiniscule** [comment]
I like that a lot - sorry just seeing this.  I'm wondering how this would work with testing functions where you define the search path as part of the function declaration.  I'll try to find some time to run a few tests.  If you're open to it, would absolutely love to have this as a part of the extension

**Comment by probablykabari** [comment]
Here's an old gist showing how: https://gist.github.com/thehesiod/d0314d599c721216f075375c667e2d9a

Basically you would change `search_path` before running your query.

This SO post has more in depth info on the procedure: https://dba.stackexchange.com/questions/69988/how-can-i-fake-inet-client-addr-for-unit-tests-in-postgresql
